Repository BanchanArt/banchan, pull requests merged in 2023-09, with the labels that each got.

#711 set up workflow to automate deploying to production on tag
  .github/github-release-from-tag.yml
  .github/release.yml
  .github/workflows/deploy_to_dev.yaml
  .github/workflows/deploy_to_prod.yaml
  .github/workflows/publish_release.yaml
  .github/workflows/publish_release_manual.yaml
  config/config.exs
  lib/banchan_web/components/layouts/root.sface
  mix.exs
  mix.lock
Labels: technical improvement

#672 Improve input fields
  config/config.exs
  lib/banchan_web/components/form/checkbox.ex
  lib/banchan_web/components/form/date_time_local_input.ex
  lib/banchan_web/components/form/email_input.ex
  lib/banchan_web/components/form/fancy_select/fancy_select.ex
  lib/banchan_web/components/form/hidden_input.ex
  lib/banchan_web/components/form/multiple_select.ex
  lib/banchan_web/components/form/number_input.ex
  lib/banchan_web/components/form/quill_input/quill_input.ex
  lib/banchan_web/components/form/select.ex
  lib/banchan_web/components/form/tags_input/tags_input.ex
  lib/banchan_web/components/form/text_input.ex
  lib/banchan_web/components/form/textarea.ex
  lib/banchan_web/components/status_badge.ex
  lib/banchan_web/live/auth_live/login_live.ex
  lib/banchan_web/live/auth_live/register_live.ex
  lib/banchan_web/live/auth_live/setup_mfa_live.ex
  lib/banchan_web/live/commission_live/index.ex
  lib/banchan_web/live/home_live/index.ex
  lib/banchan_web/live/people_live/edit.ex
  lib/banchan_web/live/studio_live/components/offering.ex
Labels: design, technical improvement, accessibility, ux

#728 store rich text as html from now on to fix weird markdown issues
  lib/banchan/accounts/user.ex
  lib/banchan/commissions/event.ex
  lib/banchan/offerings/offering.ex
  lib/banchan/reports/report.ex
  lib/banchan/rich_text.ex
  lib/banchan/studios/studio.ex
  lib/banchan/validators.ex
  lib/banchan_web/components/form/quill_input/quill_input.ex
  lib/banchan_web/components/form/quill_input/quill_input.hooks.js
  lib/banchan_web/components/rich_text.ex
  lib/banchan_web/controllers/email/commissions.ex
  lib/banchan_web/live/auth_live/account_disabled_live.ex
  lib/banchan_web/live/commission_live/components/comment.ex
  lib/banchan_web/live/commission_live/components/commission.ex
  lib/banchan_web/live/offering_live/request.ex
  lib/banchan_web/live/offering_live/show.ex
  lib/banchan_web/live/people_live/moderation.ex
  lib/banchan_web/live/report_live/show.ex
  lib/banchan_web/live/studio_live/moderation.ex
  test/banchan/accounts/settings_test.exs
  test/banchan/commissions/commissions_test.exs
  test/banchan/studios_test.exs
Labels: bug

#734 move around tip info and remove duplication
  lib/banchan_web/live/commission_live/components/balance_box.ex
  lib/banchan_web/live/commission_live/components/invoice_box.ex
  test/banchan_web/live/commission_live/invoice_test.exs
Labels: polish

#737 clarify that it's about slots remaining
  lib/banchan_web/components/offering_card.ex
Labels: polish

#738 randomize offering and studio listings in home/discover pages
  assets/js/app.js
  lib/banchan/offerings/offerings.ex
  lib/banchan/studios/studios.ex
  lib/banchan_web/live/discover_live/components/offerings.ex
  lib/banchan_web/live/discover_live/components/studios.ex
  lib/banchan_web/live/discover_live/index.ex
  lib/banchan_web/live/home_live/index.ex
  mix.exs
  mix.lock
Labels: polish

#739 body can be rich text. stop escaping it.
  lib/banchan/commissions/notifications.ex
Labels: bug

#741 Make it more obvious when it's time to pay and that an invoice is needed
  lib/banchan_web/live/commission_live/components/summary_box.ex
Labels: polish

#744 use padding instead of margins to prevent mobile page overflow
  lib/banchan_web/live/people_live/show.ex
Labels: bug, design

#746 lit-based filterable select
  assets/js/app.js
  assets/js/styles.js
  assets/package-lock.json
  assets/package.json
  assets/tailwind.config.js
  config/config.exs
  lib/banchan/payments/currency.ex
  lib/banchan_web/components/form/combo_box/combo_box.ex
  lib/banchan_web/components/form/combo_box/combo_box.hooks.ts
  lib/banchan_web/components/form/fancy_select/fancy_select.hooks.js
  lib/banchan_web/components/form/multiple_select.ex
  lib/banchan_web/live/commission_live/index.ex
  lib/banchan_web/live/people_live/moderation.ex
  lib/banchan_web/live/report_live/index.ex
  lib/banchan_web/live/report_live/show.ex
  lib/banchan_web/live/studio_live/components/offering.ex
  lib/banchan_web/live/studio_live/new.ex
  lib/banchan_web/live/studio_live/settings.ex
  package.json
  tsconfig.json
Labels: design, ux, polish

#759 fix error when getting non-200 responses from exchangerate.host
  lib/banchan/payments/payments.ex
Labels: bug

#761 Switch to captions, comment tooltips, update copy
  lib/banchan_web/components/form/checkbox.ex
  lib/banchan_web/components/form/date_time_local_input.ex
  lib/banchan_web/components/form/email_input.ex
  lib/banchan_web/components/form/multiple_select.ex
  lib/banchan_web/components/form/number_input.ex
  lib/banchan_web/components/form/quill_input/quill_input.ex
  lib/banchan_web/components/form/select.ex
  lib/banchan_web/components/form/tags_input/tags_input.ex
  lib/banchan_web/components/form/text_input.ex
  lib/banchan_web/components/form/textarea.ex
  lib/banchan_web/components/layout.ex
  lib/banchan_web/components/notifications.ex
  lib/banchan_web/components/user_handle.ex
  lib/banchan_web/live/auth_live/register_live.ex
  lib/banchan_web/live/auth_live/settings_live.ex
  lib/banchan_web/live/commission_live/components/summary_box.ex
  lib/banchan_web/live/people_live/edit.ex
  lib/banchan_web/live/people_live/moderation.ex
  lib/banchan_web/live/studio_live/components/offering.ex
  lib/banchan_web/live/studio_live/edit.ex
  lib/banchan_web/live/studio_live/moderation.ex
  lib/banchan_web/live/studio_live/new.ex
  lib/banchan_web/live/studio_live/settings.ex
Labels: accessibility, ux, polish

#762 Bring back the ComboBox component
  assets/js/app.js
  assets/js/styles.js
  assets/package-lock.json
  assets/package.json
  assets/tailwind.config.js
  config/config.exs
  lib/banchan/payments/currency.ex
  lib/banchan_web/components/form/combo_box/combo_box.ex
  lib/banchan_web/components/form/combo_box/combo_box.hooks.ts
  lib/banchan_web/components/form/fancy_select/fancy_select.hooks.js
  lib/banchan_web/components/form/multiple_select.ex
  lib/banchan_web/components/layouts/root.sface
  lib/banchan_web/live/commission_live/index.ex
  lib/banchan_web/live/people_live/moderation.ex
  lib/banchan_web/live/report_live/index.ex
  lib/banchan_web/live/report_live/show.ex
  lib/banchan_web/live/studio_live/components/offering.ex
  lib/banchan_web/live/studio_live/new.ex
  lib/banchan_web/live/studio_live/settings.ex
  package.json
  tsconfig.json
Labels: ux, polish

#766 remove studio payment currencies. let studios choose from any currenc…
  lib/banchan/studios/studio.ex
  lib/banchan_web/live/studio_live/components/offering.ex
  lib/banchan_web/live/studio_live/new.ex
  lib/banchan_web/live/studio_live/settings.ex
  priv/repo/seeds.exs
  test/banchan/studios_test.exs
  test/support/fixtures/studios_fixtures.ex
Labels: polish

#767 properly hide mature studios/offerings when mature content disabled
  lib/banchan/offerings/offerings.ex
  lib/banchan/studios/studios.ex
Labels: bug

#768 make sure allow_upload is only called once, on mount
  lib/banchan_web/live/commission_live/components/comment_box.ex
  lib/banchan_web/live/commission_live/components/summary_box.ex
  lib/banchan_web/live/offering_live/request.ex
Labels: bug

#770 fix weird scrolling issue
  lib/banchan_web/components/form/combo_box/combo_box.hooks.ts
  lib/banchan_web/components/layouts/root.sface
Labels: bug

#771 switch to explicit dates to avoid confusion about payout timing
  lib/banchan_web/live/studio_live/payouts.ex
Labels: bug

#772 Fix body overflow and add dvh rule
  lib/banchan_web/components/layouts/root.sface
Labels: bug, ux

#760 Small polishes
  lib/banchan_web/live/discover_live/components/offerings.ex
  lib/banchan_web/live/discover_live/index.ex
  lib/banchan_web/live/people_live/show.ex
  lib/banchan_web/live/studio_live/components/studio_layout.ex
Labels: polish

#773 Fix iOS overflow when focusing inputs
  assets/css/app.scss
  lib/banchan_web/components/layouts/root.sface
Labels: bug

#774 differentiate between different pound currencies
  lib/banchan/payments/currency.ex
Labels: polish
